name: Daily AI Repository Monitor

on:
  schedule:
    # Run at 10:00 UTC (3:00 AM PST)
    - cron: '0 10 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Setup environment and debug info
      run: |
        python -V
        pip list
        pwd
        ls -la
        
    - name: Create necessary directories and set permissions
      run: |
        mkdir -p logs/daily logs/weekly
        chmod -R 755 logs
        touch logs/repo_tracker.log
        chmod 644 logs/repo_tracker.log
        ls -la logs/
        
    - name: Create GitHub App private key
      run: |
        echo "${{ secrets.APP_PRIVATE_KEY }}" > github_app_private_key.pem
        chmod 600 github_app_private_key.pem
        ls -la github_app_private_key.pem
        
    - name: Run daily monitor with debug output
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_NAME: "All Repos"
        BASECAMP_ACCOUNT_ID: ${{ secrets.BASECAMP_ACCOUNT_ID }}
        BASECAMP_PROJECT_ID: ${{ secrets.BASECAMP_PROJECT_ID }}
        BASECAMP_ACCESS_TOKEN: ${{ secrets.BASECAMP_ACCESS_TOKEN }}
        APP_ID: ${{ secrets.APP_ID }}
        PRIVATE_KEY_PATH: "github_app_private_key.pem"
        INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        ANTHROPIC_TOKEN: ${{ secrets.ANTHROPIC_API_KEY }}
        ENV: "prod"
        PYTHONUNBUFFERED: "1"
      run: |
        # Run with debug logging
        python -c "import sys; print(sys.path)"
        echo "Starting daily monitor script..."
        python daily_osmonitor.py
        echo "Script completed. Checking outputs..."
        ls -la
        ls -la logs/
        
    - name: List files before upload
      if: always()
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Logs directory contents:"
        ls -la logs/ || echo "logs directory not found"
        echo "CSV files:"
        find . -name "*.csv" || echo "No CSV files found"
        echo "Log files:"
        find . -name "*.log" || echo "No log files found"

    - name: Upload logs and reports
      if: always()  # Run even if the script fails
      uses: actions/upload-artifact@v4
      with:
        name: daily-monitor-artifacts
        path: |
          logs/**/*
          *.csv
          *.log
          repo_tracker.log
        retention-days: 7
        if-no-files-found: warn
        
    - name: Clean up sensitive files
      if: always()
      run: |
        rm -f github_app_private_key.pem
        
    - name: Notify on failure
      if: failure()
      env:
        BASECAMP_ACCESS_TOKEN: ${{ secrets.BASECAMP_ACCESS_TOKEN }}
        BASECAMP_ACCOUNT_ID: ${{ secrets.BASECAMP_ACCOUNT_ID }}
        BASECAMP_PROJECT_ID: ${{ secrets.BASECAMP_PROJECT_ID }}
        BASECAMP_MESSAGE_BOARD_ID: ${{ secrets.BASECAMP_MESSAGE_BOARD_ID }}
      run: |
        curl -v -X POST "https://3.basecampapi.com/$BASECAMP_ACCOUNT_ID/buckets/$BASECAMP_PROJECT_ID/message_boards/$BASECAMP_MESSAGE_BOARD_ID/messages.json" \
          -H "Authorization: Bearer $BASECAMP_ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          -H "User-Agent: DailyOSMonitor (someone@example.com)" \
          -d '{"subject":"Daily OS Monitor Failed","content":"<p>The daily OS monitor workflow failed. Please check the GitHub Actions logs.</p>","status":"active"}'